server:
  port: 8084

spring:
  application:
    name: notification
  datasource:
    url: jdbc:postgresql://localhost:5433/notification
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: true
    show-sql: true
  rabbitmq:
    addresses: localhost:5672

#define the eureka configuration
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

# define the zipkin configuration
management:
  tracing:
    sampling:
      probability: 1.0

# define the rabbitmq configuration
rabbitmq:
  exchanges:
    internal: internal.exchange
  queue:
    notification: notification.queue
  routing-keys:
    internal-notification: internal.notification.routing-key